[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
solc_version = '0.8.28'
optimizer = true
via_ir = true
evm_version = "cancun"
optimizer_runs = 10_000
bytecode_hash = "none"
cbor_metadata = false

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[profile.deploy]
via-ir = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fuzz]
runs = 1000
max_test_rejects = 1_000_000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
